sudo: required
services:
  - docker
before_install:
  - cd docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose  
  - chmod +x /usr/local/bin/docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - echo "override default travis bundler handling; docker will setup the ruby env"
script:
  - docker-compose build
