server:
   port: 8080
kurento:
   websocket: ws://147.32.211.89:8888/kurento
asterisk:
   websocket: ws://147.32.211.89:8082/xivo
   rest:
      uri: https://147.32.211.90:5060/1.1/lines_sip
      login: test
      password: test
