server:
   port: 8080
kurento:
   websocket: ws://147.32.211.89:8888/kurento
xivo:
   websocket: ws://147.32.211.89:8082/asterisk
   rest:
      uri: https://147.32.211.90:5060/
      login: test
      password: test
